/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-18 08:17:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>AtithiStay</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/home.css\">\r\n");
      out.write("	<!-- Google Font: Poppins -->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("    <!-- Font Awesome (instead of react-icons) -->\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

String userName = (String) session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"root\">\r\n");
      out.write("\r\n");
      out.write("<!-- ================= HERO WRAPPER ================= -->\r\n");
      out.write("<div class=\"hero\">\r\n");
      out.write("\r\n");
      out.write("<!-- ================= NAVBAR WRAPPER ================= -->\r\n");
      out.write("  <nav class=\"navbar\">\r\n");
      out.write("    <h2 class=\"logo\">AtithiStay</h2>\r\n");
      out.write("\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li onclick=\"scrollToSection('home')\">Home</li>\r\n");
      out.write("        <li onclick=\"scrollToSection('about')\">About</li>\r\n");
      out.write("        <li onclick=\"scrollToSection('rooms')\">Our Rooms</li>\r\n");
      out.write("        <li onclick=\"scrollToSection('facilities')\">Facilities</li>\r\n");
      out.write("        <li onclick=\"scrollToSection('gallery')\">Gallery</li>\r\n");
      out.write("        <li onclick=\"scrollToSection('contact')\">Contact</li>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (userName != null) { 
      out.write("\r\n");
      out.write("    <li onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/mybookings.jsp'\">\r\n");
      out.write("        My Bookings\r\n");
      out.write("    </li>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ RIGHT SIDE FIXED CONTAINER -->\r\n");
      out.write("    <div class=\"nav-right\">\r\n");
      out.write("        ");
 if (userName != null) { 
      out.write("\r\n");
      out.write("            <span class=\"welcome-text\">\r\n");
      out.write("                Welcome, ");
      out.print( userName );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\"\r\n");
      out.write("               class=\"nav-login-btn\">\r\n");
      out.write("                Logout\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/user/login.jsp\"\r\n");
      out.write("               class=\"nav-login-btn\">\r\n");
      out.write("                Login\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  \r\n");
      out.write("    <!-- ================= HERO CONTENT ================= -->\r\n");
      out.write("    <div id=\"home\" class=\"hero-content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>Enjoy A Luxury Experience</h1>\r\n");
      out.write("            <p>Experience comfort and elegance in the heart of the city.</p>\r\n");
      out.write("            <button class=\"visit-btn\" onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/rooms.jsp'\">Visit Us</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"ai-card\">\r\n");
      out.write("    <h2>🤖 AI Room Assistant</h2>\r\n");
      out.write("    <p class=\"ai-subtext\">\r\n");
      out.write("        Tell us about your trip and we’ll recommend the best room for you.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <textarea\r\n");
      out.write("        class=\"ai-input\"\r\n");
      out.write("        placeholder=\"Example: Family trip to Pune for 2 nights under 6000\"\r\n");
      out.write("    ></textarea>\r\n");
      out.write("\r\n");
      out.write("    <!-- Later AI response -->\r\n");
      out.write("    <button type=\"button\" class=\"ai-btn\" onclick=\"showAIResult()\">\r\n");
      out.write("    Get AI Recommendations\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<p class=\"ai-response\" id=\"aiResult\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================= END HERO ================= -->\r\n");
      out.write("\r\n");
      out.write("<!-- ================= ROOMS ================= -->\r\n");
      out.write("<section id=\"rooms\" class=\"rooms\">\r\n");
      out.write("    <p class=\"rooms-tag\">The pleasure of luxury</p>\r\n");
      out.write("    <h2 class=\"rooms-heading\">Rooms & Suites</h2>\r\n");
      out.write("    <p class=\"rooms-subtext\">\r\n");
      out.write("        Proin consectetur non dolor vitae pulvinar. Pellentesque sollicitudin dolor eget neque viverra,\r\n");
      out.write("        sed interdum metus interdum.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"lux-rooms-grid\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"lux-room-card\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1505691938895-1758d7feb511\">\r\n");
      out.write("            <div class=\"lux-overlay\">\r\n");
      out.write("                <h3>Classic Balcony Room</h3>\r\n");
      out.write("                <p>₹4,500 / Night</p>\r\n");
      out.write("                ");
 if (userName != null) { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/booking.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/login.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"lux-room-card\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2\">\r\n");
      out.write("            <div class=\"lux-overlay\">\r\n");
      out.write("                <h3>Superior Double Room</h3>\r\n");
      out.write("                <p>₹3,000 / Night</p>\r\n");
      out.write("                ");
 if (userName != null) { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/booking.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/login.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"lux-room-card\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1551776235-dde6d482980b\">\r\n");
      out.write("            <div class=\"lux-overlay\">\r\n");
      out.write("                <h3>Deluxe Double Room</h3>\r\n");
      out.write("                <p>₹4,200 / Night</p>\r\n");
      out.write("                ");
 if (userName != null) { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/booking.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <button class=\"book-now-btn\"\r\n");
      out.write("        onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/jsp/user/login.jsp'\">\r\n");
      out.write("        Book Now →\r\n");
      out.write("    </button>\r\n");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <div class=\"view-all-wrapper\">\r\n");
      out.write("  <a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/user/rooms.jsp\"\r\n");
      out.write("     class=\"view-all-btn\">\r\n");
      out.write("    View All Rooms →\r\n");
      out.write("  </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- ================= FACILITIES ================= -->\r\n");
      out.write("<section id=\"facilities\" class=\"explore\">\r\n");
      out.write("    <span class=\"explore-tag\">Experience</span>\r\n");
      out.write("    <h2 class=\"explore-heading\">Our Hospitality</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"explore-grid\">\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-bed explore-icon\"></i>\r\n");
      out.write("            <h3>Quality Room</h3>\r\n");
      out.write("            <p>Comfortable, clean, and fully equipped rooms.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-umbrella-beach explore-icon\"></i>\r\n");
      out.write("            <h3>Private Beach</h3>\r\n");
      out.write("            <p>Peaceful private beach with scenic views.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-hotel explore-icon\"></i>\r\n");
      out.write("            <h3>Best Accommodation</h3>\r\n");
      out.write("            <p>Standard, deluxe, and luxury rooms.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-spa explore-icon\"></i>\r\n");
      out.write("            <h3>Wellness & Spa</h3>\r\n");
      out.write("            <p>Relaxing spa and wellness treatments.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-utensils explore-icon\"></i>\r\n");
      out.write("            <h3>Restaurants & Bars</h3>\r\n");
      out.write("            <p>Multi-cuisine dining experience.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"explore-card\">\r\n");
      out.write("            <i class=\"fa-solid fa-gift explore-icon\"></i>\r\n");
      out.write("            <h3>Special Offers</h3>\r\n");
      out.write("            <p>Seasonal discounts and deals.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- ================= TESTIMONIAL SECTION ================= -->\r\n");
      out.write("<section class=\"testimonials\">\r\n");
      out.write("\r\n");
      out.write("  <p class=\"test-tag\">Testimonials</p>\r\n");
      out.write("  <h2 class=\"test-heading\">What Our Guests Say</h2>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"test-grid\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CARD 1 -->\r\n");
      out.write("    <div class=\"test-card\">\r\n");
      out.write("      <img src=\"https://randomuser.me/api/portraits/women/65.jpg\" alt=\"user\" />\r\n");
      out.write("      <p>\r\n");
      out.write("        “Amazing experience! The rooms were clean, service was excellent and the location is perfect.”\r\n");
      out.write("      </p>\r\n");
      out.write("      <h4>Priya Sharma</h4>\r\n");
      out.write("      <span>Travel Blogger</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CARD 2 -->\r\n");
      out.write("    <div class=\"test-card\">\r\n");
      out.write("      <img src=\"https://randomuser.me/api/portraits/men/32.jpg\" alt=\"user\" />\r\n");
      out.write("      <p>\r\n");
      out.write("        “Luxury at its best. Everything from check-in to checkout was smooth and comfortable.”\r\n");
      out.write("      </p>\r\n");
      out.write("      <h4>Rahul Verma</h4>\r\n");
      out.write("      <span>Business Traveller</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CARD 3 -->\r\n");
      out.write("    <div class=\"test-card\">\r\n");
      out.write("      <img src=\"https://randomuser.me/api/portraits/women/45.jpg\" alt=\"user\" />\r\n");
      out.write("      <p>\r\n");
      out.write("        “Beautiful ambience and great hospitality. I will definitely visit again with my family.”\r\n");
      out.write("      </p>\r\n");
      out.write("      <h4>Sneha Patil</h4>\r\n");
      out.write("      <span>Guest</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ================= GALLERY ================= -->\r\n");
      out.write("<section id=\"gallery\" class=\"gallery\">\r\n");
      out.write("    <p class=\"gallery-tag\">Our Gallery</p>\r\n");
      out.write("    <h2 class=\"gallery-heading\">Hotel Visual Tour</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"gallery-grid\">\r\n");
      out.write("        <div class=\"gallery-item\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1582719508461-905c673771fd\">\r\n");
      out.write("            <div class=\"overlay\">Luxury Room</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"gallery-item\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1566073771259-6a8506099945\">\r\n");
      out.write("            <div class=\"overlay\">Reception</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"gallery-item\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1552566626-52f8b828add9\">\r\n");
      out.write("            <div class=\"overlay\">Dining Hall</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"gallery-item\">\r\n");
      out.write("  			<img src=\"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb\" alt=\"Swimming Pool\" />\r\n");
      out.write("  			<div class=\"overlay\">Swimming Pool</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"gallery-item\">\r\n");
      out.write("  			<img src=\"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa\" alt=\"Luxury Bedroom\" />\r\n");
      out.write("  			<div class=\"overlay\">Luxury Bedroom</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"gallery-item\">\r\n");
      out.write("  			<img src=\"https://images.unsplash.com/photo-1590490360182-c33d57733427\" alt=\"Resort View\" />\r\n");
      out.write("  			<div class=\"overlay\">Resort View</div>\r\n");
      out.write("		</div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- ================= ABOUT ================= -->\r\n");
      out.write("<section id=\"about\" class=\"about\">\r\n");
      out.write("    <div class=\"about-container\">\r\n");
      out.write("        <div class=\"about-images\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1505691938895-1758d7feb511\">\r\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-content\">\r\n");
      out.write("            <span class=\"about-tag\">About Us</span>\r\n");
      out.write("            <h2>Welcome To AtithiStay</h2>\r\n");
      out.write("            <p>We provide luxury, comfort, and world-class hospitality for every guest.</p>\r\n");
      out.write("            <p>Whether business or leisure, your stay will be memorable.</p>\r\n");
      out.write("            <button class=\"about-btn\">Discover More</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- ================= FOOTER ================= -->\r\n");
      out.write("<footer id=\"contact\" class=\"footer\">\r\n");
      out.write("  <div class=\"footer-container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-col\">\r\n");
      out.write("      <h2 class=\"footer-logo\">AtithiStay</h2>\r\n");
      out.write("      <p>Luxury and comfort in the heart of the city.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-col\">\r\n");
      out.write("      <h3>Quick Links</h3>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>Home</li>\r\n");
      out.write("        <li>Rooms</li>\r\n");
      out.write("        <li>Facilities</li>\r\n");
      out.write("        <li>Gallery</li>\r\n");
      out.write("        <li>Contact</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-col\">\r\n");
      out.write("      <h3>Contact</h3>\r\n");
      out.write("      <p>Pune, Maharashtra</p>\r\n");
      out.write("      <p>+91 98765 43210</p>\r\n");
      out.write("      <p>support@atithistay.com</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"footer-bottom\">\r\n");
      out.write("    © 2026 AtithiStay Hotel. All rights reserved.\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ================= JS ================= -->\r\n");
      out.write("<script>\r\n");
      out.write("function scrollToSection(id) {\r\n");
      out.write("    const section = document.getElementById(id);\r\n");
      out.write("    if (!section) return;\r\n");
      out.write("\r\n");
      out.write("    const yOffset = -70;\r\n");
      out.write("    const y = section.getBoundingClientRect().top + window.pageYOffset + yOffset;\r\n");
      out.write("\r\n");
      out.write("    window.scrollTo({ top: y, behavior: \"smooth\" });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function showAIResult() {\r\n");
      out.write("    document.getElementById(\"aiResult\").innerHTML =\r\n");
      out.write("        \"✨ Recommended: Deluxe Family Room under ₹6,000 with free breakfast.\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
