/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-18 07:34:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class rooms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/user/filterSidebar.jsp", Long.valueOf(1771226968302L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

List<Map<String,String>> rooms =
    (List<Map<String,String>>) request.getAttribute("availableRooms");

if (rooms != null && !rooms.isEmpty()) {
  for (Map<String,String> room : rooms) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"room-horizontal-card\">\r\n");
      out.write("  <div class=\"room-details\">\r\n");
      out.write("    <h3>");
      out.print( room.get("name") );
      out.write("</h3>\r\n");
      out.write("    <p>Type: ");
      out.print( room.get("type") );
      out.write("</p>\r\n");
      out.write("    <p>₹");
      out.print( room.get("price") );
      out.write(" / night</p>\r\n");
      out.write("    <button class=\"book-now-btn\">Book Now</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

  }
} else {

      out.write("\r\n");
      out.write(" \r\n");

}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Our Rooms</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/Rooms.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/FilterSidebar.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"rooms-page\">\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== PAGE HEADER ===== -->\r\n");
      out.write("  <section class=\"rooms-header\">\r\n");
      out.write("    <h1>Our Rooms</h1>\r\n");
      out.write("    <p>\r\n");
      out.write("      Choose from our wide range of luxury rooms and suites designed for\r\n");
      out.write("      comfort, elegance, and relaxation.\r\n");
      out.write("    </p>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== LOCATIONS ROW ===== -->\r\n");
      out.write("  <div class=\"locations-row\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"loc-item\">\r\n");
      out.write("      <span class=\"loc-text\">Bangalore <span class=\"arrow\">▼</span></span>\r\n");
      out.write("      <div class=\"loc-dropdown\">\r\n");
      out.write("        <p>Indiranagar</p>\r\n");
      out.write("        <p>Whitefield</p>\r\n");
      out.write("        <p>Koramangala</p>\r\n");
      out.write("        <p>Electronic City</p>\r\n");
      out.write("        <p>MG Road</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"loc-item\">\r\n");
      out.write("      <span class=\"loc-text\">Chennai <span class=\"arrow\">▼</span></span>\r\n");
      out.write("      <div class=\"loc-dropdown\">\r\n");
      out.write("        <p>T Nagar</p>\r\n");
      out.write("        <p>Anna Nagar</p>\r\n");
      out.write("        <p>Velachery</p>\r\n");
      out.write("        <p>OMR</p>\r\n");
      out.write("        <p>Tambaram</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <span>Delhi</span>\r\n");
      out.write("    <span>Gurgaon</span>\r\n");
      out.write("    <span>Hyderabad</span>\r\n");
      out.write("    <span>Kolkata</span>\r\n");
      out.write("    <span>Mumbai</span>\r\n");
      out.write("    <span>Pune</span>\r\n");
      out.write("    <span>Noida</span>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== MAIN LAYOUT ===== -->\r\n");
      out.write("  <div class=\"rooms-layout\">\r\n");
      out.write("\r\n");
      out.write("    <!-- FILTER SIDEBAR -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<aside class=\"filter-sidebar\">\r\n");
      out.write("\r\n");
      out.write("  <h3 class=\"filter-title\">Filter By</h3>\r\n");
      out.write("\r\n");
      out.write("  <!-- ROOM TYPE -->\r\n");
      out.write("  <div class=\"filter-group\">\r\n");
      out.write("    <h4>Room Type</h4>\r\n");
      out.write("    <div class=\"type-buttons\">\r\n");
      out.write("      <button class=\"active\">All</button>\r\n");
      out.write("      <button>Deluxe</button>\r\n");
      out.write("      <button>Superior</button>\r\n");
      out.write("      <button>Suite</button>\r\n");
      out.write("      <button>Family</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- PRICE RANGE -->\r\n");
      out.write("  <div class=\"filter-group\">\r\n");
      out.write("    <h4>Price Range</h4>\r\n");
      out.write("    <input type=\"range\" min=\"1000\" max=\"10000\" step=\"500\" value=\"10000\">\r\n");
      out.write("    <p class=\"price-text\">Up to ₹10000</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- GUESTS -->\r\n");
      out.write("  <div class=\"filter-group\">\r\n");
      out.write("    <h4>Guests</h4>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"radio\" name=\"guests\"> 1 Adult\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"radio\" name=\"guests\"> 2 Adults\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"radio\" name=\"guests\"> Family (4+)\r\n");
      out.write("    </label>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- AMENITIES -->\r\n");
      out.write("  <div class=\"filter-group\">\r\n");
      out.write("    <h4>Amenities</h4>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"checkbox\"> WiFi\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"checkbox\"> Breakfast\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"checkbox\"> AC\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"checkbox\"> Balcony\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("    <label class=\"checkbox\">\r\n");
      out.write("      <input type=\"checkbox\"> Pool\r\n");
      out.write("    </label>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ===== ROOMS LIST ===== -->\r\n");
      out.write("    <section class=\"rooms-list\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"room-horizontal-card\">\r\n");
      out.write("\r\n");
      out.write("        <!-- LEFT IMAGE -->\r\n");
      out.write("        <div class=\"room-image\">\r\n");
      out.write("          <img src=\"https://images.unsplash.com/photo-1505691938895-1758d7feb511\" alt=\"Room\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- DETAILS -->\r\n");
      out.write("        <div class=\"room-details\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"room-title\">\r\n");
      out.write("            Super Townhouse Ulsoor Near Halasuru Metro\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"room-location\">\r\n");
      out.write("            Halasuru, Bangalore • 3.6 km\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"room-rating\">\r\n");
      out.write("            ⭐ 4.3 <span>(4922 Ratings)</span>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"room-amenities\">\r\n");
      out.write("            <span>Reception</span>\r\n");
      out.write("            <span>Dining Area</span>\r\n");
      out.write("            <span>Toiletries</span>\r\n");
      out.write("            <span>+20 more</span>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- PRICE BOX -->\r\n");
      out.write("        <div class=\"room-price-box\">\r\n");
      out.write("          <div class=\"price\">\r\n");
      out.write("            ₹2442 <span>₹8984</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"discount\">72% off</div>\r\n");
      out.write("\r\n");
      out.write("          ");

String user = (String) session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
 if (user == null) { 
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/user/login.jsp\"\r\n");
      out.write("       class=\"book-now-btn\">\r\n");
      out.write("       Login to Book\r\n");
      out.write("    </a>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/bookRoom\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"roomId\" value=\"1\">\r\n");
      out.write("        <button type=\"submit\" class=\"book-now-btn\">\r\n");
      out.write("            Book Now\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
